[tool.poetry]
name = "ci-cd-homework"
version = "0.1.0"
description = ""
authors = ["Denis <den-nd.96@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
